apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: codesync
data:
  PORT: "4000"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://REPLACE_WITH_WORKER1_IP:30001"  # replace before kubectl apply
